[package]
name = "futures-rate"
version = "0.1.0"
authors = ["ZUO, JACOB <chopinsky@live.com>"]
edition = "2018"

[dependencies]
crossbeam-queue = "0.2.0"

[dev-dependencies.futures]
version = "0.3.1"
features = ["thread-pool"]
